Ecommerce page implementation
LazerPay-Finance/Lazerpay-documentation-v2 pull request #42
Opened 2022-08-24 00:02 UTC by asapconet

Ecommerce page implementation for `Use cases`

2022-08-24 21:06 UTC, Frontend-io requested changes

2022-08-24 21:06 UTC, Frontend-io commented on components/GetstartedCard/Cards.tsx
> +          className={`z-10 px-5 mb-2 bg-white md:pt-4 drop-shadow-xs rounded-8 lg:rounded-8 sm:w-auto lg:w-92 ${className}`}
Please use `className()` function here

2022-08-24 21:06 UTC, Frontend-io commented on components/GetstartedCard/Cards.tsx
>            {myIcon ? myIcon : ''}
```js
myIcon ?? ''
```

2022-08-24 21:06 UTC, Frontend-io commented on components/mdx-components.tsx
> +import { ShopifyIcon, WooCommerceIcon, WordPressIcon } from 'public/icons'
Let's not import these directly. Instead, create a component that has the cards and its detail and import the component here instead.

2022-08-24 21:06 UTC, Frontend-io commented on content/docs/use-cases/ecommerce.mdx
> +<div className='grid md:grid-cols-2 gap-8 '>
Please move this inside the component i mentioned above. The mdx file should contain purely Markdown or components, not jsx.

2022-08-26 12:01 UTC, MeisterJustice requested changes

2022-08-26 12:01 UTC, MeisterJustice commented on components/GetstartedCard/Cards.tsx
> +  customIcom?: Object
a little typo here. `customIcon not customIcom`

2022-08-30 15:39 UTC, MeisterJustice approved these changes

2022-08-30 17:10 UTC, Frontend-io approved these changes

2022-08-30 17:10 UTC, merged